name: yournextstore-cms
services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - yournextstore-volumne:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: yournextstore-cms
volumes:
  yournextstore-volumne:
    external: true
