# This for developing Payload CMS locally
name: nextstore-cms
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nextstore-cms
    volumes:
      - nextstore-volumne:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  nextstore-volumne:
